### ISSUE TITLE
Results are better without unsupervies pretraining.

### ISSUE THREAD

**Issue by zgrkpnr** [primaryobjects/deep-learning#2]
In the example I just commented out the pre-training part of the main program and I generally get a result around 466/500. With the pretraining results roughly approximates to 419/500. 

I believe you can repeat this procedure and see for yourself that the performance is getting better without the pretraining, which doesn't make sense at all. 

I am not saying that the application has problems. Maybe the Accord.net library has some bugs in terms of Deep Belief Network and corresponding learning algorithm.

**Comment by primaryobjects** [comment]
Yes, I just checked and I see the same result. It could be in the setup of the networks or the number of training iterations. Feel free to play with the settings. :)
